/* Drop Triggers */

DROP TRIGGER TRI_CART_cno;
DROP TRIGGER TRI_FREECM_comment_no;
DROP TRIGGER TRI_FREE_free_no;
DROP TRIGGER TRI_MATEAPPLY_ano;
DROP TRIGGER TRI_MATECM_mcmno;
DROP TRIGGER TRI_MATEWISH_mwno;
DROP TRIGGER TRI_MATE_mno;
DROP TRIGGER TRI_PLAN_plan_no;
DROP TRIGGER TRI_RECORD_plan_no;
DROP TRIGGER TRI_RECORD_record_no;
DROP TRIGGER TRI_REVIEW_rev_no;
DROP TRIGGER TRI_RGG_rgg_no;
DROP TRIGGER TRI_ROOM_rm_no;
DROP TRIGGER TRI_YE_CANCEL_ycno;



/* Drop Tables */

DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE FREECM CASCADE CONSTRAINTS;
DROP TABLE FREE CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE RGG CASCADE CONSTRAINTS;
DROP TABLE YEYAK CASCADE CONSTRAINTS;
DROP TABLE YE_CANCEL CASCADE CONSTRAINTS;
DROP TABLE ROOM CASCADE CONSTRAINTS;
DROP TABLE HOST CASCADE CONSTRAINTS;
DROP TABLE MATEAPPLY CASCADE CONSTRAINTS;
DROP TABLE MATECM CASCADE CONSTRAINTS;
DROP TABLE MATEWISH CASCADE CONSTRAINTS;
DROP TABLE MATE CASCADE CONSTRAINTS;
DROP TABLE RECORD CASCADE CONSTRAINTS;
DROP TABLE J_MEMBER CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_CART_cno;
DROP SEQUENCE SEQ_FREECM_comment_no;
DROP SEQUENCE SEQ_FREE_free_no;
DROP SEQUENCE SEQ_MATEAPPLY_ano;
DROP SEQUENCE SEQ_MATECM_mcmno;
DROP SEQUENCE SEQ_MATEWISH_mwno;
DROP SEQUENCE SEQ_MATE_mno;
DROP SEQUENCE SEQ_PLAN_plan_no;
DROP SEQUENCE SEQ_RECORD_plan_no;
DROP SEQUENCE SEQ_RECORD_record_no;
DROP SEQUENCE SEQ_REVIEW_rev_no;
DROP SEQUENCE SEQ_RGG_rgg_no;
DROP SEQUENCE SEQ_ROOM_rm_no;
DROP SEQUENCE SEQ_YE_CANCEL_ycno;

